name: Release Application

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Install and build UI
        run: npm install && npm run build
        working-directory: apps/desktop-ui

      - name: Install and build Controller
        run: npm install && npm run build
        working-directory: apps/controller-node
        
      - name: Install Electron dependencies
        run: npm install
        working-directory: apps/electron

      - name: Build and Release Electron App
        run: npm run dist
        working-directory: apps/electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
